#!/usr/bin/with-contenv bash

# update sma installation
echo "[init-sma-config] Updating SMA from github master."
git -C ${SMA_PATH} pull origin master --quiet

# check virtual python environment
if [[ ! -f "${SMA_PATH}/venv/bin/python3" ]]; then
    echo "[init-sma-config] Creating python virtual environment."
    python3 -m venv ${SMA_PATH}/venv
    ${SMA_PATH}/venv/bin/python3 -m pip install -q --upgrade pip --no-cache-dir > /dev/null
fi

# update project requirements
echo "[init-sma-config] Installing/updating SMA project requirements."
${SMA_PATH}/venv/bin/pip install -q --no-cache-dir \
        -r ${SMA_PATH}/setup/requirements.txt \
        -r ${SMA_PATH}/setup/requirements-deluge.txt \
        -r ${SMA_PATH}/setup/requirements-qbittorrent.txt > /dev/null

# permissions
chown -R abc:abc ${SMA_PATH}

# setup autoprocess
${SMA_PATH}/venv/bin/python3 ${SMA_PATH}/setup.py

exit $?